updated-documentation
FifthTry/ftd.dev pull request #6
Opened 2022-05-23 09:50 UTC by arcoprova

updated documentation on ftd.dev/id page, ftd.dev/text page, ftd.dev/input page.

2022-05-23 11:14 UTC, amitu commented on alternatives.ftd
> +sub-sections: $config.why-header
Why did you do this? Remove toc/sub-sections parameters from everywhere.

2022-05-26 05:34 UTC, Arpita-Jaiswal requested changes

2022-05-26 05:34 UTC, Arpita-Jaiswal commented on FPM.ftd
> +-- fpm.dependency: fifthtry.github.io/brand-switcher as bs
Remove this and also check if it's imported anywhere. `brand-switcher` is now known as `product-switcher`

2022-05-26 06:50 UTC, Arpita-Jaiswal requested changes

2022-05-26 06:50 UTC, Arpita-Jaiswal commented on FPM.ftd
>  -- fpm.dependency: fifthtry.github.io/product-switcher as ps
```suggestion
-- fpm.dependency: fifthtry.github.io/product-switcher as ps
```

Don't add dependencies twice. Remove the first one. and try to build it locally.

2022-05-26 10:37 UTC, Arpita-Jaiswal requested changes

2022-05-26 10:37 UTC, Arpita-Jaiswal commented on FPM/config.ftd
> +
Why have we added this?

2022-05-26 10:37 UTC, Arpita-Jaiswal commented on examples/comic.ftd
> +-- ft.page: Once upon a time...
Why twice?

2022-05-26 10:37 UTC, Arpita-Jaiswal commented on id.ftd
> +
Are we using it anywhere?

2022-05-30 06:25 UTC, closed without merging